// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 水水水果API.Models.RMS;

public partial class Coupon
{
    public int Id { get; set; }

    public string DiscountId { get; set; }

    public int BrandId { get; set; }

    public DateTime ExpireType { get; set; }

    public string Code { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime LastUpdateDate { get; set; }

    public bool IsActive { get; set; }
}