// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace 水水水果API.Models.RMS;

[Table("Currency")]
public partial class Currency
{
    [Key]
    public int Id { get; set; }

    public int BrandId { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string Code { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    [Required]
    [StringLength(50)]
    public string Symbol { get; set; }

    public int DecimalPlaces { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdateDate { get; set; }
}