// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 水水水果API.Models.RMS;

public partial class CustomerCoupon
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public int CouponId { get; set; }

    public int BrandId { get; set; }

    public DateTime ExpireDate { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime LastUpdateDate { get; set; }
}