// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace 水水水果API.Models.RMS;

[Table("Discount")]
[Index("Code", Name = "UQ__Discount__A25C5AA720FFBB7F", IsUnique = true)]
public partial class Discount
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Code { get; set; }

    [Required]
    [StringLength(255)]
    public string Description { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column(TypeName = "decimal(10, 4)")]
    public decimal Value { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal MinSubtotal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpireDate { get; set; }

    public bool IsActive { get; set; }

    public bool IsCombinable { get; set; }

    public bool IsAutoApplied { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdateDate { get; set; }
}