// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace 水水水果API.Models.RMS;

[Table("MileageScheme")]
public partial class MileageScheme
{
    [Key]
    public int Id { get; set; }

    public int BrandId { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Code { get; set; }

    public int EarnPerAmount { get; set; }

    [Column(TypeName = "decimal(10, 4)")]
    public decimal EarningRate { get; set; }

    public int RedemptionRate { get; set; }

    public int MinRedemption { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string ExpiredType { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpireDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdateDate { get; set; }
}