// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace 水水水果API.Models.RMS;

[Table("Order")]
public partial class Order
{
    [Key]
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public int? CurrencyId { get; set; }

    public int BrandId { get; set; }

    public int StoreId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string OrderStatus { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal OrderAmountTotal { get; set; }

    [Required]
    [StringLength(255)]
    public string ShippingAddress { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdateDate { get; set; }
}