// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace 水水水果API.Models.RMS;

[Table("ShoppingCart")]
public partial class ShoppingCart
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string SessionId { get; set; }

    public int UserId { get; set; }

    public int ProductId { get; set; }

    public int? DicountId { get; set; }

    public int Quantity { get; set; }

    [Column("Unit_Price", TypeName = "decimal(18, 2)")]
    public decimal UnitPrice { get; set; }

    public bool IsDiscount { get; set; }

    [Column("Discount_Amount", TypeName = "decimal(18, 2)")]
    public decimal DiscountAmount { get; set; }

    [Column("Original_Price", TypeName = "decimal(18, 2)")]
    public decimal OriginalPrice { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdateDate { get; set; }

    public bool IsActive { get; set; }

    [Required]
    [Column("Source_Channel")]
    [StringLength(50)]
    public string SourceChannel { get; set; }
}