// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace 水水水果API.Models.RMS;

[Table("TransactionItem")]
public partial class TransactionItem
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    [Required]
    [StringLength(255)]
    public string Description { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal PriceUnitOriginal { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal PriceUnitPaid { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal SubTotalPaid { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal DiscountItemAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal MileageItemAmount { get; set; }

    public int BrandId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdateDate { get; set; }

    public bool IsActive { get; set; }
}