// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace 水水水果API.Models.CRM;

[Table("CustomerGroup")]
public partial class CustomerGroup
{
    [Key]
    public int Id { get; set; }

    [Column("name")]
    public int Name { get; set; }

    [Column("type")]
    public int Type { get; set; }

    [StringLength(255)]
    public string Description { get; set; } = null!;

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdateDate { get; set; }
}