// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace 水水水果API.Models.CRM;

[Table("Customer")]
public partial class Customer
{
    [Key]
    public int Id { get; set; }

    public int BrandId { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; } = null!;

    [StringLength(50)]
    public string LastName { get; set; } = null!;

    [StringLength(50)]
    public string Address { get; set; } = null!;

    [StringLength(2)]
    public string? Gender { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime BirthDay { get; set; }

    [StringLength(10)]
    public string? Phone { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdateDate { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Member> Members { get; set; } = new List<Member>();
}