// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 水水水果API.Models.CRM;

public partial class MemberTier
{
    public int? MemberTierId { get; set; }

    public int BrandId { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime LastUpdateDate { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();
}