// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 水水水果API.Models.CRM;

public partial class Member
{
    public int? MemberId { get; set; }

    public int CustomerId { get; set; }

    public int? MemberTierId { get; set; }

    public int BrandId { get; set; }

    public int StoreId { get; set; }

    public string Email { get; set; }

    public string PassWord { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime LastUpdateDate { get; set; }

    public bool IsActive { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public string Provider { get; set; }

    public string ProviderId { get; set; }

    public string ProviderEmail { get; set; }

    public string AvatarUrl { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual MemberTier MemberTier { get; set; }
}