// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace 水水水果API.Models.CRM;

public partial class TWCRM_TESTContext : DbContext
{
    public TWCRM_TESTContext(DbContextOptions<TWCRM_TESTContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<MemberTier> MemberTiers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Customer__3214EC07DE2DE93F");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<CustomerGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Customer__3214EC07C8EECF20");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Member__3214EC07C8DB42FC");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Customer).WithMany(p => p.Members)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Member_Customer");

            entity.HasOne(d => d.MemberTier).WithMany(p => p.Members).HasConstraintName("FK_Member_MemberTier");
        });

        modelBuilder.Entity<MemberTier>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MemberTi__3214EC073DC5DA03");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}