// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 水水水果API.Models.ERP;

public partial class User
{
    public int Id { get; set; }

    public int DepartmentId { get; set; }

    public int RoleId { get; set; }

    public string UserName { get; set; }

    public string PassWord { get; set; }

    public string Email { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public DateTime Birthday { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime LastUpdateDate { get; set; }

    public bool IsActive { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public string Provider { get; set; }

    public string ProviderId { get; set; }

    public string ProviderEmail { get; set; }

    public string AvatarUrl { get; set; }
}